### PR TITLE
Process API

### PR DESCRIPTION
**Pull request by bergie**
Contains the component changes from #64 rebased on latest

### CODE REVIEW

**Comment by trustmaster** [comment]
What keeps this one from merging?

**Comment by bergie** [comment]
@trustmaster waiting for NoFlo 0.8.0

**Comment by trustmaster** [comment]
@bergie i've started releasing `-beta1` libraries as well depending on 0.8 beta to be able to run a complete test on a real project you know. So i think it would make sense to merge this PR and release a beta of `noflo-math` as well.

**Comment by bergie** [comment]
Fair point

**Comment by bergie** [comment]
@trustmaster released as `0.1.0-beta1`

**Pull request merged**
