### PR TITLE
Updated chai to version 3.3.0

### PR DESCRIPTION
**Pull request by kentcdodds**
:rocket:

One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.

You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.

Have a good day!

---

This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.

<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks like @greenkeeperio-bot is having trouble with these PRs... cc @boennemann... Why did I open this PR? Also, @bergie opened a PR on one of mine as well...

**Comment by bergie** [comment]
@kentcdodds related to https://twitter.com/greenkeeperio/status/648869834529374208

**Comment by kentcdodds** [comment]
Ah, very good. Thanks!

**Comment by boennemann** [comment]
@kentcdodds We had a problem with a shared GitHub API client in memory. We've identified the problem and stopped the cause. We've identified all falsely attributed pull-requests and are in the process of notifying every single affected user.

We are deeply sorry for this.

Best,
Stephan

**Pull request merged**
